onEvent('item.registry', e => {

  //Raw//
  e.create('berseria_sky:raw_cobalt').displayName('§9Raw Cobalt')
  e.create('berseria_sky:raw_aluminum').displayName('§fRaw Aluminum')
  e.create('berseria_sky:raw_copper').displayName('Raw Copper')
  e.create('berseria_sky:raw_osmium').displayName('Raw Osmium')
  e.create('berseria_sky:raw_gold').displayName('§eRaw Gold')
  e.create('berseria_sky:raw_iron').displayName('§7Raw Iron')
  e.create('berseria_sky:raw_lead').displayName('Raw Lead')
  e.create('berseria_sky:raw_nickel').displayName('Raw Nickel')
  e.create('berseria_sky:raw_silver').displayName('§8Raw Silver')
  e.create('berseria_sky:raw_zinc').displayName('Raw Zinc')
  e.create('berseria_sky:raw_uranium').displayName('§2Raw Uranium')
  e.create('berseria_sky:raw_tin').displayName('Raw Tin')
  e.create('berseria_sky:raw_ardite').displayName('§cRaw Ardite')
  e.create('blue_skies:raw_falsite').displayName('Raw Falsite')
  e.create('blue_skies:raw_ventium').displayName('Raw Ventium')
  e.create('blue_skies:raw_horizonite').displayName('Raw Horizonite')
  e.create('blue_skies:raw_aquite').displayName('Raw Aquite')
  e.create('blue_skies:raw_charoite').displayName('Raw Charoite')

  //Crushed//
  e.create('crushed_ardite_ore').displayName('§cCrushed Ardite Ore')
  e.create('blue_skies:crushed_falsite_ore').displayName('Crushed Falsite Ore')
  e.create('blue_skies:crushed_ventium_ore').displayName('Crushed Ventium Ore')
  e.create('blue_skies:crushed_horizonite_ore').displayName('Crushed Horizonite Ore')

  //Ore_Piece//
  e.create('berseria_sky:cobalt_piece_ore').displayName('Cobalt Ore Piece')
  e.create('berseria_sky:gold_piece_ore').displayName('Gold Ore Piece')
  e.create('berseria_sky:ardite_piece_ore').displayName('Ardite Ore Piece')
  e.create('berseria_sky:aluminum_piece_ore').displayName('Aluminum Ore Piece')
  e.create('berseria_sky:iron_piece_ore').displayName('Iron Ore Piece')
  e.create('berseria_sky:lead_piece_ore').displayName('Lead Ore Piece')
  e.create('berseria_sky:nickel_piece_ore').displayName('Nickel Ore Piece')
  e.create('berseria_sky:silver_piece_ore').displayName('§8Silver Ore Piece')
  e.create('berseria_sky:tin_piece_ore').displayName('Tin Ore Piece')
  e.create('berseria_sky:uranium_piece_ore').displayName('§2Uranium Ore Piece')
  e.create('berseria_sky:zinc_piece_ore').displayName('Zinc Ore Piece')
  e.create('berseria_sky:copper_piece_ore').displayName('Copper Ore Piece')
  e.create('berseria_sky:osmium_piece_ore').displayName('Osmium Ore Piece')
  e.create('berseria_sky:prosperity_piece_ore').displayName('Prosperity Ore Piece')
  e.create('berseria_sky:soulium_piece_ore').displayName('Soulium Ore Piece')

  //Seed//                                              
  e.create('inferium_seed').displayName('§eInferium Seed Base')
  e.create('prudentium_seed').displayName('§2Prudentium Seed Base')
  e.create('tertium_seed').displayName('§6Tertium Seed Base')
  e.create('imperium_seed').displayName('§9Imperium Seed Base')
  e.create('supremium_seed').displayName('§cSupremium Seed Base')
  e.create('insanium_seed').displayName('§5Insanium Seed Base')
  e.create('ornium_seed').displayName('§dOrnium Seed Base').glow(true)
  e.create('lightium_seed').displayName('§3Lightium Seed Base').glow(true)
  e.create('tornium_seed').displayName('§7Tornium Seed Base')
  e.create('ouranium_seed').displayName('§2Ouranium Seed Base')


  //Essence//
  e.create('lightium_essence').displayName('§3Lightium Essence').glow(true)
  e.create('ornium_essence').displayName('§dOrnium Essence').glow(true)
  e.create('tornium_essence').displayName('§7Tornium Essence')
  e.create('ouranium_essence').displayName('§2Ouranium Essence')

  //Ingot//
  e.create('berseria_sky:elinvonze_ingot').displayName('Elinvonze Ingot')
  e.create('berseria_sky:manyerium_ingot').displayName('§5Manyerium Ingot')
  e.create('berseria_sky:fayronium_ingot').displayName('§4Fayronium Ingot')
  e.create('berseria_sky:comerald_ingot').displayName('Comerald Ingot')
  e.create('berseria_sky:god_ingot').displayName('§cGod Ingot')
  e.create('platinum_ingot').displayName('§bPlatinum Ingot')
  e.create('ardite_ingot').displayName('§cArdite Ingot')
  e.create('diamond_ingot').displayName('§bDiamond Ingot')
  e.create('emerald_ingot').displayName('§2Emerald Ingot')
  e.create('ornium_ingot').displayName('§dOrnium Ingot').glow(true)
  e.create('ornium_gemstone').displayName('§dOrnium Gemstone').glow(true)
  e.create('lightium_ingot').displayName('§3Lightium Ingot').glow(true)
  e.create('lightium_gemstone').displayName('§3Lightium Gemstone').glow(true)
  e.create('ouranium_ingot').displayName('§2Ouranium Ingot')
  e.create('ouranium_gemstone').displayName('§2Ouranium Gemstone')
  e.create('tornium_gemstone').displayName('§7Tornium Gemstone')
  e.create('tornium_ingot').displayName('§7Tornium Ingot')
  e.create('sun_ingot').displayName('§eSun Ingot')
  e.create('moon_ingot').displayName('§8Moon Ingot')
  e.create('wither_skeleton_ingot').displayName('Wither Ingot')
  e.create('berseria_sky:queens_steel_ingot').displayName('§2Queen`s Steel Ingot')
  e.create('berseria_sky:manronium_steel_ingot').displayName('§6Manronium Steel Ingot')
  e.create('mekanism:ingot_antimatter').displayName('Antimatter Ingot')
  e.create('tinkers_reforged:blazing_copper_ingot').displayName('Blazing Copper Ingot')
  
  

  //Nugget//
  e.create('berseria_sky:elinvonze_nugget').displayName('Elinvonze Nugget')
  e.create('berseria_sky:manyerium_nugget').displayName('§5Manyerium Nugget')
  e.create('berseria_sky:fayronium_nugget').displayName('§4Fayronium Nugget')
  e.create('berseria_sky:comerald_nugget').displayName('Comerald Nugget')
  e.create('berseria_sky:god_nugget').displayName('§cGod Nugget')
  e.create('berseria_sky:queens_steel_nugget').displayName('§2Queen`s Steel Nugget')
  e.create('berseria_sky:manronium_steel_nugget').displayName('§6Manronium Steel Nugget')
  e.create('blue_skies:falsite_nugget').displayName('Falsite Nugget')
  e.create('blue_skies:horizonite_nugget').displayName('Horizonite Nugget')
  e.create('blue_skies:ventium_nugget').displayName('Ventium Nugget')
  e.create('platinum_nugget').displayName('§bPlatinum Nugget')
  e.create('diamond_nugget').displayName('§bDiamond Nugget')
  e.create('ardite_nugget').displayName('§cArdite Nugget')
  e.create('ornium_nugget').displayName('§dOrnium Nugget').glow(true)
  e.create('lightium_nugget').displayName('§3Lightium Nugget').glow(true)
  e.create('sun_nugget').displayName('§eSun Nugget')
  e.create('moon_nugget').displayName('§8Moon Nugget')
  e.create('tornium_nugget').displayName('§7Tornium Nugget')
  e.create('ouranium_nugget').displayName('§2Ouranium Nugget')
  e.create('emerald_nugget').displayName('§2Emerald Nugget')
  e.create('mekanism:nugget_antimatter').displayName('Antimatter Nugget')
  e.create('tinkers_reforged:blazing_copper_nugget').displayName('Blazing Copper Nugget')
  


  //Plate//
  e.create('awakened_draconium_plate').displayName('Awakened Draconium Plate')
  e.create('ardite_plate').displayName('§cArdite Plate')
  e.create('mekanism:antimatter_plate').displayName('Antimatter Plate')
  e.create('alfsteel_plate').displayName('Alfsteel Plate')
  e.create('crystaltine_plate').displayName('§eCrystaltine Plate')
  e.create('enhanced_ender_plate').displayName('§eEnhanced Ender Plate')
  e.create('cobalt_plate').displayName('Cobalt Plate')
  e.create('manyullyn_plate').displayName('Manyullyn Plate')
  e.create('hepatizon_plate').displayName('Hepatizon Plate')
  e.create('pig_iron_plate').displayName('Pig Iron Plate')
  e.create('queens_slime_plate').displayName('Queens Slime Plate')
  e.create('pink_slime_ingot_plate').displayName('Pink Slime Ingot Plate')
  e.create('cyanite_plate').displayName('Cyanite Plate')
  e.create('hop_graphite_plate').displayName('HOP Graphite Plate')
  e.create('osmium_plate').displayName('Osmium Plate')
  e.create('refined_glowstone_plate').displayName('Refined Glowstone Plate')
  e.create('refined_obsidian_plate').displayName('Refined Obsidian Plate')
  e.create('berseria_sky:elinvonze_plate').displayName('Elinvonze Plate')
  e.create('berseria_sky:manyerium_plate').displayName('§5Manyerium Plate')
  e.create('berseria_sky:fayronium_plate').displayName('§4Fayronium Plate')
  e.create('yellorium_plate').displayName('Yellorium Plate')
  e.create('draconium_plate').displayName('Draconium Plate')
  e.create('redstone_plate').displayName('§4Redstone Plate')
  e.create('soulium_plate').displayName('Soulium Plate')
  e.create('prosperity_plate').displayName('Prosperity Plate')
  e.create('inferium_plate').displayName('§eInferium Plate')
  e.create('prudentium_plate').displayName('§2Prudentium Plate')
  e.create('tertium_plate').displayName('§6Tertium Plate')
  e.create('imperium_plate').displayName('§9Imperium Plate')
  e.create('supremium_plate').displayName('§cSupremium Plate')
  e.create('insanium_plate').displayName('§5Insanium Plate')
  e.create('ornium_plate').displayName('§dOrnium Plate').glow(true)
  e.create('lightium_plate').displayName('§3Lightium Plate').glow(true)
  e.create('tornium_plate').displayName('§7Tornium Plate')
  e.create('ouranium_plate').displayName('§2Ouranium Plate')
  e.create('starmetal_plate').displayName('Starmetal Plate')
  e.create('platinum_plate').displayName('§bPlatinum Plate')
  e.create('manasteel_plate').displayName('§bManasteel Plate')
  e.create('terrasteel_plate').displayName('Terrasteel Plate')
  e.create('elementium_plate').displayName('Elementium Plate')
  e.create('falsite_plate').displayName('Falsite Plate')
  e.create('horizonite_plate').displayName('Horizonite Plate')
  e.create('ventium_plate').displayName('Ventium Plate')
  e.create('rose_gold_plate').displayName('Rose Gold Plate')
  e.create('slimesteel_plate').displayName('Slimesteel Plate')
  e.create('diamond_plate').displayName('§3Diamond Plate')
  e.create('emerald_plate').displayName('§2Emerald Plate')
  e.create('ender_plate').displayName('Ender Plate')
  e.create('fairy_plate').displayName('Fairy Plate')
  e.create('sun_plate').displayName('§eSun Plate')
  e.create('moon_plate').displayName('§8Moon Plate')
  e.create('berseria_sky:queens_steel_plate').displayName('§2Queen`s Steel Plate')
  e.create('berseria_sky:manronium_steel_plate').displayName('§6Manronium Steel Plate')
  e.create('ultimate_plate').displayName('§4Ultimate Plate')
  e.create('berseria_sky:comerald_plate').displayName('Comerald Plate')


  //Gear//
  e.create('awakened_draconium_gear').displayName('Awakened Draconium Gear')
  e.create('ardite_gear').displayName('§cArdite Gear')
  e.create('aluminium_gear').displayName('Aluminium Gear')
  e.create('mekanism:antimatter_gear').displayName('Antimatter Gear')
  e.create('alfsteel_gear').displayName('Alfsteel Gear')
  e.create('crystaltine_gear').displayName('§eCrystaltine Gear')
  e.create('enhanced_ender_gear').displayName('§eEnhanced Ender Gear')
  e.create('brass_gear').displayName('Brass Gear')
  e.create('cobalt_gear').displayName('Cobalt Gear')
  e.create('manyullyn_gear').displayName('Manyullyn Gear')
  e.create('hepatizon_gear').displayName('Hepatizon Gear')
  e.create('pig_iron_gear').displayName('Pig Iron Gear')
  e.create('queens_slime_gear').displayName('Queens Slime Gear')
  e.create('pink_slime_ingot_gear').displayName('Pink Slime Ingot Gear')
  e.create('cyanite_gear').displayName('Cyanite Gear')
  e.create('hop_graphite_gear').displayName('HOP Graphite Gear')
  e.create('osmium_gear').displayName('Osmium Gear')
  e.create('draconium_gear').displayName('Draconium Gear')
  e.create('ender_gear').displayName('Ender Gear')
  e.create('elementium_gear').displayName('Elementium Gear')
  e.create('falsite_gear').displayName('Falsite Gear')
  e.create('ventium_gear').displayName('Ventium Gear')
  e.create('horizonite_gear').displayName('Horizonite Gear')
  e.create('rose_gold_gear').displayName('Rose Gold Gear')
  e.create('slimesteel_gear').displayName('Slimesteel Gear')
  e.create('berseria_sky:elinvonze_gear').displayName('Elinvonze Gear')
  e.create('berseria_sky:manyerium_gear').displayName('§5Manyerium Gear')
  e.create('berseria_sky:fayronium_gear').displayName('§5Fayronium Gear')
  e.create('manasteel_gear').displayName('Manasteel Gear')
  e.create('terrasteel_gear').displayName('terrasteel Gear')
  e.create('refined_obsidian_gear').displayName('Refined obsidian Gear')
  e.create('refined_glowstone_gear').displayName('Refined Glowstone Gear')
  e.create('redstone_gear').displayName('§4Redstone Gear')
  e.create('soulium_gear').displayName('Soulium Gear')
  e.create('prosperity_gear').displayName('Prosperity Gear')
  e.create('inferium_gear').displayName('§eInferium Gear')
  e.create('prudentium_gear').displayName('§2Prudentium Gear')
  e.create('tertium_gear').displayName('§6Tertium Gear')
  e.create('imperium_gear').displayName('§9Imperium Gear')
  e.create('supremium_gear').displayName('§cSupremium Gear')
  e.create('insanium_gear').displayName('§5Insanium Gear')
  e.create('ornium_gear').displayName('§dOrnium Gear').glow(true)
  e.create('lightium_gear').displayName('§3Lightium Gear').glow(true)
  e.create('tornium_gear').displayName('§7Tornium Gear')
  e.create('ouranium_gear').displayName('§2Ouranium Gear')
  e.create('steel_gear').displayName('Steel Gear')
  e.create('fairy_gear').displayName('Fairy Gear')
  e.create('sun_gear').displayName('§eSun Gear')
  e.create('moon_gear').displayName('§8Moon Gear')
  e.create('starmetal_gear').displayName('Starmetal Gear')
  e.create('platinum_gear').displayName('§bPlatinum Gear')
  e.create('berseria_sky:queens_steel_gear').displayName('§5Queen`s Steel Gear')
  e.create('berseria_sky:manronium_steel_gear').displayName('§6Manronium Steel Gear')
  e.create('uranium_gear').displayName('Uranium Gear')
  e.create('yellorium_gear').displayName('Yellorium Gear')
  e.create('zinc_gear').displayName('Zinc Gear')
  e.create('steel_energized_gear').displayName('Energized Steel Gear')
  e.create('ultimate_gear').displayName('§4Ultimate Gear')
  e.create('berseria_sky:comerald_gear').displayName('Comerald Gear')

  //Dust//
  e.create('ardite_dust').displayName('Ardite Dust')
  e.create('cobalt_dust').displayName('Cobalt Dust')
  e.create('platinum_dust').displayName('§bPlatinum Dust')
  e.create('tconstruct:manyullyn_dust').displayName('Manyullyn Dust')
  e.create('create:brass_dust').displayName('Brass Dust')
  e.create('create:zinc_dust').displayName('Zinc Dust')
  e.create('thermal:dust_cryotheum').displayName('Cryotheum Dust')
  e.create('thermal:dust_petrotheum').displayName('Petrotheum Dust')
  e.create('thermal:dust_pyrotheum').displayName('Pyrotheum Dust')
  e.create('thermal:dust_aerotheum').displayName('Aerotheum Dust')
  e.create('thermal:dust_mana').displayName('Mana Dust')
  e.create('berseria_sky:queens_steel_dust').displayName('§5Queens Steel Dust')
  e.create('berseria_sky:manyerium_dust').displayName('Manyerium Dust')
  e.create('berseria_sky:fayronium_dust').displayName('§4Fayronium Dust')
  e.create('berseria_sky:manronium_steel_dust').displayName('§6Manronium_steel Dust')
  e.create('tinkers_reforged:blazing_copper_dust').displayName('Blazing Copper Dust')
  e.create('extendedcrafting:crystaltine_dust').displayName('Crystaltine Dust')
  e.create('berseria_sky:dirty_dust_crystaltine').displayName('Dirty Crystaltine Dust')

  //Coal//
  e.create('ornium_coal').displayName('§dOrnium Coal').burnTime(150000)
  e.create('lightium_coal').displayName('§3Lightium Coal').burnTime(300000)
  e.create('tornium_coal').displayName('§7Tornium Coal').burnTime(600000)
  e.create('ouranium_coal').displayName('§2Ouranium Coal').burnTime(1000000)

  //SolarFlux//
  e.create('photovoltaic_cell_7').displayName('Photovoltaic Cell VII (Wyvern)')
  e.create('photovoltaic_cell_8').displayName('Photovoltaic Cell VIII (Draconic)')
  e.create('photovoltaic_cell_9').displayName('Photovoltaic Cell IX (Chaotic)')
  e.create('photovoltaic_cell_10').displayName('Photovoltaic Cell X (Fayronium)')
  e.create('photovoltaic_cell_11').displayName('Photovoltaic Cell XI (Queens Steel)')
  e.create('photovoltaic_cell_12').displayName('Photovoltaic Cell XII (Manyerium)')
  e.create('photovoltaic_cell_13').displayName('Photovoltaic Cell XIII (Manronium Steel)')
  e.create('ultimate_photovoltaic_cell').displayName('§5Ultimate Photovoltaic Cell')
  e.create('photovoltaic_cell_14').displayName('Neutronium Photovoltaic Cell')
  e.create('photovoltaic_cell_15').displayName('Infinity Photovoltaic Cell')


  //Other//
  e.create('compactmachines:machine_wall_break').displayName('Machine Wall Incomplete')
  e.create('bedrock').displayName('Bedrock')
  e.create('wither_skeleton_fragment').displayName('§eWither Skeleton Fragment')
  e.create('simplyjetpacks:thruster_te6').displayName('Fluxed Thruster (Manronium Steel)')
  e.create('berseria_sky:manronium_steel_augment').displayName('Manronium Steel Component')
  e.create('minecraft:amethyst_shard').displayName('Amethyst Shard')
  e.create('berseria_sky:black_amethyst_shard').displayName('Black Amethyst Shard')

  //Enriched//
  e.create('berseria_sky:enriched_manyullyn').displayName('Enriched Manyullyn')
  e.create('berseria_sky:enriched_manyerium').displayName('Enriched Manyerium')
  e.create('berseria_sky:enriched_insanium').displayName('Enriched Insanium')
  e.create('berseria_sky:enriched_manronium_steel').displayName('Enriched Manronium Steel')

  //Slurry//
  e.create('berseria_sky:crystaltine_clump').displayName('Crystaltine Clump')
  e.create('berseria_sky:crystaltine_crystal').displayName('Crystaltine Crystal')
  e.create('berseria_sky:crystaltine_shard').displayName('Crystaltine Shard')
  

  //Crystal//
  e.create('berseria_sky:prosperity_crystal').displayName('Empty Prosperity Crystal').unstackable()
  e.create('insanium_crystal').displayName('§5Insanium Infusion Crystal').unstackable()
  e.create('ornium_crystal').displayName('§dOrnium Infusion Crystal').unstackable()
  e.create('lightium_crystal').displayName('§3Lightium Infusion Crystal').unstackable()
  e.create('tornium_crystal').displayName('§7Tornium Infusion Crystal').unstackable()


  //Creative//
  e.create('creative_ingot').displayName('§5Creative Ingot').glow(true)
  e.create('creative_plate').displayName('§5Creative Plate').glow(true)
  e.create('berseria_sky:creative_augment_base').displayName('§5Creative Augment Base')
  e.create('berseria_sky:infinite_control_circuit').displayName('§cInfinite Control Circuit')
  e.create('berseria_sky:alloy_infinity').displayName('§cInfinity Alloy')
  e.create('berseria_sky:enriched_infinity').displayName('§cEnriched Infinity')

  //Cake//
  e.create('berseria_sky:dirt_dough').displayName('Dirt Dough')
  e.create('berseria_sky:base_dirt_cake').displayName('Base Dirt Cake')
  e.create('berseria_sky:baked_dirt_cake').displayName('Baked Dirt Cake')
  e.create('berseria_sky:soulsand_dough').displayName('Soul Sand Dough')
  e.create('berseria_sky:base_soulsand_cake').displayName('Base Soul Sand Cake')
  e.create('berseria_sky:baked_soulsand_cake').displayName('Baked Soul Sand Cake')
  e.create('berseria_sky:obsidian_dough').displayName('Obsidian Dough')
  e.create('berseria_sky:base_obsidian_cake').displayName('Base Obsidian Cake')
  e.create('berseria_sky:baked_obsidian_cake').displayName('Baked Obsidian Cake')

  //Spécial//
  e.create('berseria_sky:lumium_core').displayName('Lumium Core')
  e.create('berseria_sky:enderium_core').displayName('Enderium Core')
  e.create('berseria_sky:manyerium_core').displayName('Manyerium Core')
  e.create('berseria_sky:queens_steel_core').displayName('Queens Steel Core')
  e.create('berseria_sky:fayronium_core').displayName('Fayronium Core')
  e.create('berseria_sky:manronium_steel_core').displayName('Manronium Steel Core')
  e.create('berseria_sky:ball_of_hakai').displayName('Ball Of Hakai')
  e.create('berseria_sky:empty_addon').displayName('Empty Addon')
  e.create('berseria_sky:enderman_cake').displayName('Enderman Cake')
  e.create('berseria_sky:creeper_cake').displayName('Creeper Cake')
  e.create('berseria_sky:velvetcrowe_ingot').displayName('Velvet Crowe Ingot')
  

  //Beta Testeur//
  e.create('berseria_sky:beyond_kev_ingot').displayName('Beyond Kev Ingot')
  e.create('berseria_sky:drimoz_ingot').displayName('DrimoZ Ingot')
  e.create('berseria_sky:reps_ingot').displayName('Reps Ingot')
  e.create('berseria_sky:myraft_ingot').displayName('MyRaft Ingot')
  e.create('berseria_sky:coks_ingot').displayName('Coks1306 Ingot')
  e.create('berseria_sky:mldeg_ingot').displayName('MLDEG Ingot')
  e.create('berseria_sky:clauclau_ingot').displayName('ClauClauQC Ingot')
  e.create('berseria_sky:sayaniku_ingot').displayName('Sayaniku Ingot')




  onEvent('item.modification', event => {
    event.modify(['minecraft:ender_pearl'], item => {
      item.maxStackSize = 64
      item.fireResistant = true
    })
  })
  onEvent('item.modification', event => {
    event.modify(['extendedcrafting:ultimate_singularity','minecraft:egg','minecraft:bucket',/powah:ender_gate/], item => {
      item.maxStackSize = 64
    })
  })




})