#
#Elite Botany Pot Speed
#Range: > 1
eliteBotanyPotSpeed = 4
#
#Ultra Botany Pot Speed
#Range: > 1
ultraBotanyPotSpeed = 8
#
#Creative Botany Pot Speed
#Range: > 1
creativeBotanyPotSpeed = 64
#
#Elite Botany Pot Multiplier
#Range: > 1
eliteBotanyPotMultiplier = 4
#
#Ultra Botany Pot Multiplier
#Range: > 1
ultraBotanyPotMultiplier = 8
#
#Creative Botany Pot Multiplier
#Range: > 1
creativeBotanyPotMultiplier = 64

