
#Debug settings
[debugMode]
	#Set false to stop output log.
	debugMode = false

#General settings
[general]
	#Set it to change volume.
	#Range: 4000 ~ 96000
	volume = 32000
	#Whether the drawer retains fluid when destroyed.
	retainFluid = true

