#A list of modid:entity_name entries that will be blocked from spawning.
entityBlockList = ["minecraft:wandering_trader", "rats:plague_doctor"]
#Entity spawn prevention radius (in chunks)
#Range: 4 ~ 12
radius = 12
#Disable all spawns of entities in entityBlockList?
disableSpawns = false

