
[General]
	#The number of item stacks held in a basic unit of storage.
	#1x1 drawers hold 8 units, 1x2 drawers hold 4 units, 2x2 drawers hold 2 units.
	#Half-depth drawers hold half those amounts.
	baseStackStorage = 4
	#Controller range defines how far away a drawer can be connected
	#on X, Y, or Z planes.  The default value of 50 gives the controller a very
	#large range, but not beyond the chunk load distance.
	#Range: 1 ~ 75
	controllerRange = 25
	enableUI = true
	enableSidedInput = true
	enableSidedOutput = true
	enableItemConversion = true
	enableExtraCompactingRules = true
	debugTrace = false
	#List of rules in format "domain:item1, domain:item2, n".
	#Creates a compacting drawer rule to convert 1 of item1 into n of item2.
	compactingRules = ["excompressum:compressed_sand,minecraft:sand,9", "industrialforegoing:dryrubber,industrialforegoing:tinydryrubber,9", "mysticalagriculture:soulium_dust,berseria_sky:soulium_piece_ore,4", "mysticalagriculture:prosperity_shard,berseria_sky:prosperity_piece_ore,4", "minecraft:clay, minecraft:clay_ball, 4", "berseria_sky:raw_cobalt, berseria_sky:cobalt_piece_ore, 4", "berseria_sky:raw_ardite, berseria_sky:ardite_piece_ore, 4", "berseria_sky:raw_iron, berseria_sky:iron_piece_ore, 4", "berseria_sky:raw_zinc, berseria_sky:zinc_piece_ore, 4", "berseria_sky:raw_nickel, berseria_sky:nickel_piece_ore, 4", "berseria_sky:raw_gold, berseria_sky:gold_piece_ore, 4", "berseria_sky:raw_copper, berseria_sky:copper_piece_ore, 4", "berseria_sky:raw_lead, berseria_sky:lead_piece_ore, 4", "berseria_sky:raw_aluminum, berseria_sky:aluminum_piece_ore, 4", "berseria_sky:raw_silver, berseria_sky:silver_piece_ore, 4", "berseria_sky:raw_tin, berseria_sky:tin_piece_ore, 4", "berseria_sky:raw_uranium, berseria_sky:uranium_piece_ore, 4", "berseria_sky:raw_osmium, berseria_sky:osmium_piece_ore, 4", "minecraft:wither_skeleton_skull, kubejs:wither_skeleton_fragment, 9"]

[StorageUpgrades]
	#Storage upgrades multiply storage capacity by the given amount.
	#When multiple storage upgrades are used together, their multipliers are added before being applied.
	level1Mult = 4
	level2Mult = 8
	level3Mult = 16
	level4Mult = 32
	level5Mult = 64

[Integration]
	#When true, shows quantity as NxS + R (by stack size) rather than count
	wailaStackRemainder = true
	#When true, does not show current quantities unless quantify key was used
	wailaRespectQuantifyKey = false

