onEvent('item.tags', event => {

    //Raw and Piece//
    event.add('forge:ores/cobalt', 'berseria_sky:raw_cobalt')
    event.add('forge:ores/ardite', ['berseria_sky:raw_ardite', 'kubejs:ardite_ore'])
    event.add('forge:ore_pieces', ['berseria_sky:prosperity_piece_ore','berseria_sky:cobalt_piece_ore', 'berseria_sky:ardite_piece_ore', 'berseria_sky:copper_piece_ore', 'berseria_sky:gold_piece_ore', 'berseria_sky:iron_piece_ore', 'berseria_sky:lead_piece_ore', 'berseria_sky:nickel_piece_ore', 'berseria_sky:silver_piece_ore', 'berseria_sky:tin_piece_ore', 'berseria_sky:uranium_piece_ore', 'berseria_sky:zinc_piece_ore', 'berseria_sky:aluminum_piece_ore', 'berseria_sky:osmium_piece_ore'])
    event.add('forge:ores/copper', 'berseria_sky:raw_copper')
    event.add('forge:ores/nickel', 'berseria_sky:raw_nickel')
    event.add('forge:ores/aluminum', 'berseria_sky:raw_aluminum')
    event.add('forge:ores/gold', 'berseria_sky:raw_gold')
    event.add('forge:ores/iron', 'berseria_sky:raw_iron')
    event.add('forge:ores/lead', 'berseria_sky:raw_lead')
    event.add('forge:ores/tin', 'berseria_sky:raw_tin')
    event.add('forge:ores/zinc', 'berseria_sky:raw_zinc')
    event.add('forge:ores/uranium', 'berseria_sky:raw_uranium')
    event.add('forge:ores/silver', 'berseria_sky:raw_silver')
    event.add('forge:ores/osmium', 'berseria_sky:raw_osmium')
    event.add('forge:ores/rock_crystal', 'astralsorcery:rock_crystal_ore')
    event.add('forge:ores/aquamarine', 'astralsorcery:aquamarine_sand_ore')
    event.add('blue_skies:ores/aquite', 'blue_skies:raw_aquite')
    event.add('blue_skies:ores/charoite', 'blue_skies:raw_charoite')
    event.add('blue_skies:ores/falsite', 'blue_skies:raw_falsite')
    event.add('blue_skies:ores/ventium', 'blue_skies:raw_ventium')
    event.add('blue_skies:ores/horizonite', 'blue_skies:raw_horizonite')


    //Crushed//
    event.add('create:crushed_ores', 'kubejs:crushed_ardite_ore')
    event.add('crushed:ore/ardite', 'kubejs:crushed_ardite_ore')
    event.add('create:crushed_ores', 'blue_skies:crushed_falsite_ore')
    event.add('crushed:ore/falsite', 'blue_skies:crushed_falsite_ore')
    event.add('create:crushed_ores', 'blue_skies:crushed_ventium_ore')
    event.add('crushed:ore/ventium', 'blue_skies:crushed_ventium_ore')
    event.add('create:crushed_ores', 'blue_skies:crushed_horizonite_ore')
    event.add('crushed:ore/horizonite', 'blue_skies:crushed_horizonite_ore')
    event.add('crushed:ore/cobalt', 'morecreatestuffs:crushed_cobalt_ore')


    //Other//
    event.add('itemfilters:check_nbt', ['extendedcrafting:singularity','immersiveengineering:blueprint'])
    event.add('forge:planks', ['minecraft:acacia_planks', 'minecraft:dark_oak_planks', 'minecraft:crimson_planks', 'minecraft:warped_planks', 'minecraft:oak_planks', 'minecraft:spruce_planks', 'minecraft:birch_planks', 'minecraft:jungle_planks'])
    event.add('forge:slabs', ['minecraft:oak_slab', 'minecraft:spruce_slab', 'minecraft:birch_slab', 'minecraft:jungle_slab', 'minecraft:acacia_slab', 'minecraft:dark_oak_slab', 'minecraft:crimson_slab', 'minecraft:warped_slab'])
    event.add('forge:log', ['minecraft:oak_log', 'minecraft:spruce_log', 'minecraft:birch_log', 'minecraft:jungle_log', 'minecraft:acacia_log', 'minecraft:dark_oak_log'])
    event.add('forge:stripped/wood', ['minecraft:stripped_oak_wood', 'minecraft:stripped_spruce_wood', 'minecraft:stripped_birch_wood', 'minecraft:stripped_jungle_wood', 'minecraft:stripped_acacia_wood','tconstruct:stripped_greenheart_wood', 'tconstruct:stripped_skyroot_wood', 'tconstruct:stripped_bloodshroom_wood', 'sonicraft:stripped_ghz_palm_wood'])
    event.add('forge:rubber', 'industrialforegoing:tinydryrubber')
    event.add('forge:leaves', ['minecraft:oak_leaves', 'minecraft:spruce_leaves', 'minecraft:birch_leaves', 'minecraft:jungle_leaves', 'minecraft:dark_oak_leaves', 'minecraft:acacia_leaves'])
    event.add('forge:dragon_scales', ['mysticalagradditions:dragon_scale', 'cagedmobs:dragon_scale'])

    //Tags//
    event.add('forge:nuggets', ['berseria_sky:elinvonze_nugget','kubejs:platinum_nugget', 'kubejs:ardite_nugget', 'berseria_sky:manyerium_nugget', 'berseria_sky:queens_steel_nugget', 'berseria_sky:fayronium_nugget', 'berseria_sky:manronium_steel_nugget'])
    event.add('forge:ingots', ['tinkers_reforged:blazing_copper_ingot','kubejs:ardite_ingot', 'kubejs:wither_skeleton_ingot', 'extendedcrafting:redstone_ingot', 'berseria_sky:manyerium_ingot', 'berseria_sky:queens_steel_ingot', 'berseria_sky:fayronium_ingot', 'berseria_sky:manronium_steel_ingot'])
    event.add('forge:dusts', ['tinkers_reforged:blazing_copper_dust','kubejs:platinum_dust','kubejs:ardite_dust','kubejs:cobalt_dust'])
    event.add('forge:ores', ['berseria_sky:raw_ardite', 'kubejs:ardite_ore'])
    event.add('forge:ores/crystaltine', 'kubejs:crystaltine_ore')
    event.add('forge:storage_blocks', ['tinkers_reforged:blazing_copper_block','kubejs:ardite_block', 'berseria_sky:manyerium_block', 'berseria_sky:queens_steel_block', 'berseria_sky:fayronium_block', 'berseria_sky:manronium_steel_block', 'berseria_sky:raw_cobalt_block', 'berseria_sky:raw_ardite_block', 'berseria_sky:raw_aluminum_block', 'berseria_sky:raw_silver_block', 'berseria_sky:raw_iron_block', 'berseria_sky:raw_tin_block', 'berseria_sky:raw_zinc_block', 'berseria_sky:raw_uranium_block', 'berseria_sky:raw_lead_block', 'berseria_sky:raw_nickel_block', 'berseria_sky:raw_gold_block', 'berseria_sky:raw_copper_block', 'kubejs:emerald_block', 'kubejs:sun_block', 'endless:infinity_block', 'kubejs:pink_slime_ingot_block', 'kubejs:fertilized_block', 'kubejs:platinum_block', 'kubejs:moon_block'])
    event.add('forge:plates', ['berseria_sky:elinvonze_plate','kubejs:redstone_plate', 'kubejs:starmetal_plate', 'kubejs:diamond_plate', 'kubejs:emerald_plate', 'berseria_sky:manyerium_plate', 'berseria_sky:fayronium_plate', 'berseria_sky:queens_steel_plate', 'berseria_sky:manronium_steel_plate', 'kubejs:manasteel_plate', 'kubejs:cobalt_plate', 'kubejs:ardite_plate', 'kubejs:manyullyn_plate','kubejs:hop_graphite_plate'])
    event.add('forge:gears', ['berseria_sky:elinvonze_gear','kubejs:redstone_gear', 'berseria_sky:manyerium_gear', 'berseria_sky:fayronium_gear', 'berseria_sky:queens_steel_gear', 'berseria_sky:manronium_steel_gear', 'kubejs:hop_graphite_gear'])
    event.add('tconstruct:anvil_metal', ['berseria_sky:manronium_steel_block', 'berseria_sky:manyerium_block', 'kubejs:emerald_block', 'kubejs:sun_block', 'endless:infinity_block', 'kubejs:pink_slime_ingot_block', 'kubejs:fertilized_block', 'kubejs:platinum_block', 'kubejs:ardite_block', 'kubejs:moon_block', 'berseria_sky:queens_steel_block', 'berseria_sky:fayronium_block', 'kubejs:diamond_block', 'kubejs:aquamarine_block', 'kubejs:ender_biotite_block', 'kubejs:certus_quartz_crystal_charged_block', 'berseria_sky:elinvonze_block', 'kubejs:wither_skeleton_ingot_block', 'extendedcrafting:the_ultimate_block', 'kubejs:hop_graphite_block'])
    event.add('forge:eggs', 'minecraft:turtle_egg')
    event.add('thermal:crafting/dies', ['appliedenergistics2:engineering_processor_press', 'appliedenergistics2:calculation_processor_press', 'appliedenergistics2:logic_processor_press', 'appliedenergistics2:silicon_press'])
   
    

    //Log Tag//
    event.add('forge:sakura_log', ['betternether:striped_log_nether_sakura', 'betternether:nether_sakura_log', 'betternether:nether_sakura_bark', 'betternether:striped_bark_nether_sakura'])
    event.add('forge:anchor_log', ['betternether:striped_log_anchor_tree', 'betternether:striped_bark_anchor_tree', 'betternether:anchor_tree_log', 'betternether:anchor_tree_bark'])
    event.add('forge:willow_log', ['betternether:striped_log_willow', 'betternether:striped_bark_willow', 'betternether:willow_log', 'betternether:willow_bark'])
    event.add('forge:rubeus_log', ['betternether:rubeus_log', 'betternether:rubeus_bark', 'betternether:striped_log_rubeus', 'betternether:striped_bark_rubeus'])
    event.add('forge:mushroom_fir_log', ['betternether:mushroom_fir_log', 'betternether:mushroom_fir_wood', 'betternether:striped_log_mushroom_fir', 'betternether:striped_wood_mushroom_fir'])
    event.add('forge:wart_log', ['betternether:wart_log', 'betternether:wart_bark', 'betternether:striped_log_wart', 'betternether:striped_bark_wart'])
    event.add('forge:stalagnate_log', ['betternether:stalagnate_log', 'betternether:stalagnate_bark', 'betternether:striped_log_stalagnate', 'betternether:striped_bark_stalagnate'])
    

    //Add Gear//
    event.add('forge:gears/redstone', 'kubejs:redstone_gear')
    event.add('forge:gears/elinvonze', 'berseria_sky:elinvonze_gear')
    event.add('forge:gears/manyerium', 'berseria_sky:manyerium_gear')
    event.add('forge:gears/ardite', 'kubejs:ardite_gear')
    event.add('forge:gears/brass', 'kubejs:brass_gear')
    event.add('forge:gears/cobalt', 'kubejs:cobalt_gear')
    event.add('forge:gears/moon', 'kubejs:moon_gear')
    event.add('forge:gears/aluminum', 'kubejs:aluminium_gear')
    event.add('forge:gears/antimatter', 'mekanism:antimatter_gear')
    event.add('forge:gears/osmium', 'kubejs:osmium_gear')
    event.add('forge:gears/steel', 'kubejs:steel_gear')
    event.add('forge:gears/manyullyn', 'kubejs:manyullyn_gear')
    event.add('forge:gears/rose_gold', 'kubejs:rose_gold_gear')
    event.add('forge:gears/platinum', 'kubejs:platinum_gear')
    event.add('forge:gears/fayronium', 'berseria_sky:fayronium_gear')
    event.add('forge:gears/queens_steel', 'berseria_sky:queens_steel_gear')
    event.add('forge:gears/manronium_steel', 'berseria_sky:manronium_steel_gear')
    event.add('forge:gears/uranium', 'kubejs:uranium_gear')
    event.add('forge:gears/zinc', 'kubejs:zinc_gear')


    //Add Ingots//
    event.add('forge:ingots/platinum', 'kubejs:platinum_ingot')
    event.add('forge:ingots/antimatter', 'mekanism:ingot_antimatter')
    event.add('forge:ingots/ardite', 'kubejs:ardite_ingot')
    event.add('forge:ingots/elinvonze', 'berseria_sky:elinvonze_ingot')
    event.add('forge:ingots/wither', 'kubejs:wither_skeleton_ingot')
    event.add('forge:ingots/redstone', 'extendedcrafting:redstone_ingot')
    event.add('forge:ingots/manyerium', 'berseria_sky:manyerium_ingot')
    event.add('forge:ingots/queens_steel', 'berseria_sky:queens_steel_ingot')
    event.add('forge:ingots/fayronium', 'berseria_sky:fayronium_ingot')
    event.add('forge:ingots/manronium_steel', 'berseria_sky:manronium_steel_ingot')
    event.add('forge:ingots/blazing_copper', 'tinkers_reforged:blazing_copper_ingot')


    //Add Dust//
    event.add('forge:dusts/ardite', 'kubejs:ardite_dust')
    event.add('forge:dusts/cobalt', 'kubejs:cobalt_dust')
    event.add('forge:dusts/platinum', 'kubejs:platinum_dust')
    event.add('forge:dusts/brass', 'create:brass_dust')
    event.add('forge:dusts/zinc', 'create:zinc_dust')
    event.add('forge:dusts/manyullyn', 'tconstruct:manyullyn_dust')
    event.add('forge:dusts/blazing_copper', 'tinkers_reforged:blazing_copper_dust')

    //Add Block//
    event.add('forge:storage_blocks/raw_aluminum', 'berseria_sky:raw_aluminum_block')
    event.add('forge:storage_blocks/raw_ardite', 'berseria_sky:raw_ardite_block')
    event.add('forge:storage_blocks/raw_copper', 'berseria_sky:raw_copper_block')
    event.add('forge:storage_blocks/raw_cobalt', 'berseria_sky:raw_cobalt_block')
    event.add('forge:storage_blocks/raw_osmium', 'berseria_sky:raw_osmium_block')
    event.add('forge:storage_blocks/raw_gold', 'berseria_sky:raw_gold_block')
    event.add('forge:storage_blocks/raw_iron', 'berseria_sky:raw_iron_block')
    event.add('forge:storage_blocks/raw_tin', 'berseria_sky:raw_tin_block')
    event.add('forge:storage_blocks/raw_nickel', 'berseria_sky:raw_nickel_block')
    event.add('forge:storage_blocks/raw_silver', 'berseria_sky:raw_silver_block')
    event.add('forge:storage_blocks/raw_lead', 'berseria_sky:raw_lead_block')
    event.add('forge:storage_blocks/raw_uranium', 'berseria_sky:raw_uranium_block')
    event.add('forge:storage_blocks/raw_zinc', 'berseria_sky:raw_zinc_block')
    event.add('forge:storage_blocks/ardite', 'kubejs:ardite_block')
    event.add('forge:storage_blocks/elinvonze', 'berseria_sky:elinvonze_block')
    event.add('forge:storage_blocks/manyerium', 'berseria_sky:manyerium_block')
    event.add('forge:storage_blocks/queens_steel', 'berseria_sky:queens_steel_block')
    event.add('forge:storage_blocks/fayronium', 'berseria_sky:fayronium_block')
    event.add('forge:storage_blocks/platinum', 'kubejs:platinum_block')
    event.add('forge:storage_blocks/manronium_steel', 'berseria_sky:manronium_steel_block')
    event.add('forge:storage_blocks/blazing_copper', 'tinkers_reforged:blazing_copper_block')
    event.add('forge:storage_blocks/raw_falsite', 'blue_skies:raw_falsite_block')
    event.add('forge:storage_blocks/raw_horizonite', 'blue_skies:raw_horizonite_block')
    event.add('forge:storage_blocks/raw_ventium', 'blue_skies:raw_ventium_block')
    event.add('forge:storage_blocks/raw_aquite', 'blue_skies:raw_aquite_block')
    event.add('forge:storage_blocks/raw_charoite', 'blue_skies:raw_charoite_block')


    //Add Plate//
    event.add('forge:plates/redstone', 'kubejs:redstone_plate')
    event.add('forge:plates/elinvonze', 'berseria_sky:elinvonze_plate')
    event.add('forge:plates/manyerium', 'berseria_sky:manyerium_plate')
    event.add('forge:plates/antimatter', 'mekanism:antimatter_plate')
    event.add('forge:plates/ardite', 'kubejs:ardite_plate')
    event.add('forge:plates/cobalt', 'kubejs:cobalt_plate')
    event.add('forge:plates/osmium', 'kubejs:osmium_plate')
    event.add('forge:plates/platinum', 'kubejs:platinum_plate')
    event.add('forge:plates/rose_gold', 'kubejs:rose_gold_plate')
    event.add('forge:plates/manyullyn', 'kubejs:manyullyn_plate')
    event.add('forge:plates/starmetal', 'kubejs:starmetal_plate')
    event.add('forge:plates/diamond', 'kubejs:diamond_plate')
    event.add('forge:plates/emerald', 'kubejs:emerald_plate')
    event.add('forge:plates/manasteel', 'kubejs:manasteel_plate')
    event.add('forge:plates/fayronium', 'berseria_sky:fayronium_plate')
    event.add('forge:plates/queens_steel', 'berseria_sky:queens_steel_plate')
    event.add('forge:plates/manronium_steel', 'berseria_sky:manronium_steel_plate')
    event.add('forge:plates/hop_graphite', 'kubejs:hop_graphite_plate')

/************************************************Removed**********************************************/
    //Nugget//
    event.remove('forge:nuggets/lead', ['immersiveengineering:nugget_lead', 'mekanism:nugget_lead'])
    event.remove('forge:nuggets/electrum', ['immersiveengineering:nugget_electrum'])
    event.remove('forge:nuggets/steel', ['immersiveengineering:nugget_steel'])
    event.remove('forge:nuggets/aluminum', ['tinkers_reforged:aluminum_nugget'])
    event.remove('forge:nuggets/tin', ['mekanism:nugget_tin'])
    event.remove('forge:nuggets/silver', ['immersiveengineering:nugget_silver'])
    event.remove('forge:nuggets/nickel', ['immersiveengineering:nugget_nickel'])
    event.remove('forge:nuggets/uranium', ['immersiveengineering:nugget_uranium'])
    event.remove('forge:nuggets/copper', ['immersiveengineering:nugget_copper', 'tconstruct:copper_nugget'])
    event.remove('forge:nuggets/constantan', ['immersiveengineering:nugget_constantan'])
    event.remove('forge:nuggets/bronze', ['mekanism:nugget_bronze'])
    event.remove('forge:nuggets/platinum', ['morecreatestuffs:platinum_nugget'])
    

    //Ore//
    event.remove('forge:ores/uranium', ['exnihilosequentia:chunk_uranium', 'bigreactors:yellorite_ore','immersiveengineering:ore_uranium'])
    event.remove('forge:ores/aluminum', ['exnihilosequentia:chunk_aluminum','tinkers_reforged:aluminum_ore'])
    event.remove('forge:ores/lead', ['mekanism:lead_ore', 'exnihilosequentia:chunk_lead','immersiveengineering:ore_lead'])
    event.remove('forge:ores/iron', ['exnihilosequentia:chunk_iron'])
    event.remove('forge:ores/tin', ['exnihilosequentia:chunk_tin', 'mekanism:tin_ore'])
    event.remove('forge:ores/zinc', ['exnihilosequentia:chunk_zinc'])
    event.remove('forge:ores/nickel', ['exnihilosequentia:chunk_nickel'])
    event.remove('forge:ores/silver', ['exnihilosequentia:chunk_silver', 'immersiveengineering:ore_silver'])
    event.remove('forge:ores/gold', ['exnihilosequentia:chunk_gold'])
    event.remove('forge:ores/nickel', ['immersiveengineering:ore_nickel'])
    event.remove('forge:ores/copper', ['mekanism:copper_ore', 'tconstruct:copper_ore', 'exnihilosequentia:chunk_copper', 'create:copper_ore','immersiveengineering:ore_copper'])
    event.remove('forge:ores/platinum', ['exnihilosequentia:chunk_platinum'])
    event.remove('forge:ores/uraninite_dense', ['powah:uraninite_ore_dense'])
    event.remove('forge:ores/uraninite_poor', ['powah:uraninite_ore_poor'])
    event.remove('forge:ores/certus_quartz', ['appliedenergistics2:charged_quartz_ore'])
    event.remove('forge:ores', ['powah:uraninite_ore_dense', 'create:copper_ore', 'powah:uraninite_ore_poor','immersiveengineering:ore_uranium'])


    //Ingots//
    event.remove('forge:ingots/lead', ['immersiveengineering:ingot_lead', 'mekanism:ingot_lead', 'exnihilosequentia:ingot_lead'])
    event.remove('forge:ingots/silver', ['immersiveengineering:ingot_silver', 'exnihilosequentia:ingot_silver'])
    event.remove('forge:ingots/steel', ['immersiveengineering:ingot_steel'])
    event.remove('forge:ingots/platinum', ['exnihilosequentia:ingot_platinum'])
    event.remove('forge:ingots/uranium', ['bigreactors:yellorium_ingot', 'immersiveengineering:ingot_uranium', 'exnihilosequentia:ingot_uranium'])
    event.remove('forge:ingots/yellorium', ['mekanism:ingot_uranium'])
    event.remove('forge:ingots/electrum', ['immersiveengineering:ingot_electrum'])
    event.remove('forge:ingots/copper', ['immersiveengineering:ingot_copper', 'mekanism:ingot_copper', 'create:copper_ingot', 'tconstruct:copper_ingot'])
    event.remove('forge:ingots/tin', ['mekanism:ingot_tin', 'exnihilosequentia:ingot_tin'])
    event.remove('forge:ingots/constantan', ['immersiveengineering:ingot_constantan'])
    event.remove('forge:ingots/nickel', ['immersiveengineering:ingot_nickel', 'exnihilosequentia:ingot_nickel'])
    event.remove('forge:ingots/zinc', ['exnihilosequentia:ingot_zinc'])
    event.remove('forge:ingots/aluminum', ['exnihilosequentia:ingot_aluminum','tinkers_reforged:aluminum_ingot'])
    event.remove('forge:ingots/bronze', ['mekanism:ingot_bronze'])



    //Dust//
    event.remove('forge:dusts/uranium', ['immersiveengineering:dust_uranium', 'bigreactors:yellorium_dust'])
    event.remove('forge:dusts/bronze', ['mekanism:dust_bronze'])
    event.remove('forge:dusts/coal', ['mekanism:dust_coal'])
    event.remove('forge:dusts/constantan', ['immersiveengineering:dust_constantan'])
    event.remove('forge:dusts/nickel', ['immersiveengineering:dust_nickel'])
    event.remove('forge:dusts/electrum', ['immersiveengineering:dust_electrum'])
    event.remove('forge:dusts/copper', ['mekanism:dust_copper', 'immersiveengineering:dust_copper'])
    event.remove('forge:dusts/lead', ['immersiveengineering:dust_lead', 'mekanism:dust_lead'])
    event.remove('forge:dusts/silver', ['immersiveengineering:dust_silver'])
    event.remove('forge:dusts/gold', ['immersiveengineering:dust_gold', 'mekanism:dust_gold', 'appliedenergistics2:gold_dust'])
    event.remove('forge:dusts/iron', ['appliedenergistics2:iron_dust', 'mekanism:dust_iron', 'immersiveengineering:dust_iron'])
    event.remove('forge:dusts/tin', ['mekanism:dust_tin'])
    event.remove('forge:dusts/steel', ['immersiveengineering:dust_steel'])
    event.remove('forge:dusts/netherite', ['mekanism:dust_netherite'])
    event.remove('forge:dusts/sulfur', ['mekanism:dust_sulfur', 'immersiveengineering:dust_sulfur'])
    event.remove('forge:dusts/wood', ['immersiveengineering:dust_wood', 'mekanism:sawdust'])
    event.remove('forge:dusts/diamond', ['mekanism:dust_diamond'])
    event.remove('forge:dusts/obsidian', ['mekanism:dust_obsidian'])
    event.remove('forge:dusts/lapis', ['mekanism:dust_lapis_lazuli'])
    event.remove('forge:dusts/aluminum', ['tinkers_reforged:aluminum_dust'])
    event.remove('forge:dusts/quartz', ['appliedenergistics2:nether_quartz_dust', 'mekanism:dust_quartz'])

    //Blocks//
    event.remove('forge:storage_blocks/bronze', ['mekanism:block_bronze'])
    event.remove('forge:storage_blocks/copper', ['mekanism:block_copper', 'tconstruct:copper_block', 'create:copper_block', 'immersiveengineering:storage_copper'])
    event.remove('forge:storage_blocks/nickel', ['immersiveengineering:storage_nickel'])
    event.remove('forge:storage_blocks/silver', ['immersiveengineering:storage_silver'])
    event.remove('forge:storage_blocks/lead', ['mekanism:block_lead', 'immersiveengineering:storage_lead'])
    event.remove('forge:storage_blocks/tin', ['mekanism:block_tin'])
    event.remove('forge:storage_blocks/uranium', ['immersiveengineering:storage_uranium'])
    event.remove('forge:storage_blocks/steel', ['immersiveengineering:storage_steel'])
    event.remove('forge:storage_blocks/coal_coke', ['immersiveengineering:coke'])
    event.remove('forge:storage_blocks/charcoal', ['quark:charcoal_block', 'mekanism:block_charcoal'])

    //Plate//
    event.remove('forge:plates/constantan', ['immersiveengineering:plate_constantan'])
    event.remove('forge:plates/electrum', ['immersiveengineering:plate_electrum'])
    event.remove('forge:plates/lead', ['immersiveengineering:plate_lead'])
    event.remove('forge:plates/silver', ['immersiveengineering:plate_silver'])
    event.remove('forge:plates/nickel', ['immersiveengineering:plate_nickel'])
    event.remove('forge:plates/copper', ['immersiveengineering:plate_copper', 'create:copper_sheet'])
    event.remove('forge:plates/gold', ['immersiveengineering:plate_gold', 'create:golden_sheet'])
    event.remove('forge:plates/iron', ['immersiveengineering:plate_iron', 'create:iron_sheet'])

    //Other//
    event.remove('forge:rods/wooden', ['immersiveengineering:stick_treated'])
    event.remove('forge:rods/iron', ['immersiveengineering:stick_iron'])
    event.remove('forge:rods/copper', ['immersiveposts:stick_copper'])
    event.remove('forge:dyes/yellow', ['mekanism:dust_sulfur'])
    event.remove('forge:barrels/wooden', ['betterendforge:mossy_glowshroom_barrel', 'betterendforge:lacugrove_barrel', 'betterendforge:end_lotus_barrel', 'betterendforge:pythadendron_barrel', 'betterendforge:dragon_tree_barrel', 'betterendforge:tenanea_barrel', 'betterendforge:helix_tree_barrel', 'betterendforge:umbrella_tree_barrel', 'betterendforge:jellyshroom_barrel', 'betterendforge:lucernia_barrel'])
    event.remove('forge:slag', ['immersiveengineering:slag'])
    event.remove('forge:wires/copper', ['immersiveengineering:wire_copper'])
    event.remove('forge:bitumen', ['immersivepetroleum:bitumen'])
   

    //Tags//
    event.remove('forge:dusts', ['mekanism:dust_gold', 'appliedenergistics2:nether_quartz_dust', 'mekanism:dust_quartz','mekanism:dust_obsidian'])
    event.remove('forge:ores', ['immersiveengineering:ore_silver','tinkers_reforged:aluminum_ore'])
    event.remove('forge:nuggets', ['tconstruct:copper_nugget','tinkers_reforged:aluminum_nugget'])
    event.remove('forge:ingots', ['create:copper_ingot','tinkers_reforged:aluminum_ingot'])
    event.remove('forge:stone', ['quark:marble'])
    event.remove('forge:coal_coke', ['immersiveengineering:coal_coke'])
    event.remove('forge:plates', ['immersiveengineering:plate_silver'])
    event.remove('forge:wires', ['immersiveengineering:wire_copper'])
    event.remove('forge:gears/gold', ['hammerlib:gears/gold'])
    event.remove('forge:gears/iron', ['hammerlib:gears/iron'])
    event.remove('forge:chests', ['quark:oak_chest','quark:spruce_chest'])

})
